# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApodCli < Formula
  desc "A command-line tool to browse the NASA Astronomy Picture of the Day archive."
  homepage "https://github.com/marcusziade/homebrew-apod-cli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/marcusziade/apod-cli/releases/download/v0.0.2/apod-cli_0.0.2_darwin_arm64.tar.gz"
      sha256 "c0f7a5c18220eefbe8f258ded877dc277954cdd42430b4b1316d475a2acda579"

      def install
        bin.install "apod-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/apod-cli/releases/download/v0.0.2/apod-cli_0.0.2_darwin_amd64.tar.gz"
      sha256 "e2da9517646b65c853837482c5adadae39a696a3bb145b6100706fded2a82225"

      def install
        bin.install "apod-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/apod-cli/releases/download/v0.0.2/apod-cli_0.0.2_linux_arm64.tar.gz"
      sha256 "21446a0b82015e395417c8a5deeb752e994d8ce1c4bc031eebbff8d52a4081a9"

      def install
        bin.install "apod-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/apod-cli/releases/download/v0.0.2/apod-cli_0.0.2_linux_amd64.tar.gz"
      sha256 "bbe407f60e0f6189fe519e69727b0e919bab100bc1583e59872f3b2e2dfe20ab"

      def install
        bin.install "apod-cli"
      end
    end
  end
end
