# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ApodCli < Formula
  desc "A command-line tool to browse the NASA Astronomy Picture of the Day archive."
  homepage "https://github.com/marcusziade/homebrew-apod-cli"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/marcusziade/apod-cli/releases/download/v0.0.4/apod-cli_0.0.4_darwin_arm64.tar.gz"
      sha256 "56c66d9a54e89a76f7b81332da1c032f66ac7af02a348f0e1f331ba8cd1c3165"

      def install
        bin.install "apod-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/apod-cli/releases/download/v0.0.4/apod-cli_0.0.4_darwin_amd64.tar.gz"
      sha256 "286f839d30ca77789ea33eafa2b7c0e58934bb89f943253aaae55dfd3ae15fa6"

      def install
        bin.install "apod-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcusziade/apod-cli/releases/download/v0.0.4/apod-cli_0.0.4_linux_arm64.tar.gz"
      sha256 "d0a6fced0221220939f6df7d29a480aa13e002c49dea07a49ef1638cdd35a677"

      def install
        bin.install "apod-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcusziade/apod-cli/releases/download/v0.0.4/apod-cli_0.0.4_linux_amd64.tar.gz"
      sha256 "48b81aaf83e9fd3d6bcc5c055f0d8407100e76215c703203ac226f97def17945"

      def install
        bin.install "apod-cli"
      end
    end
  end
end
